permissions:
  contents: read
  packages: write # Gehitu baimen hau

- name: Login to GitHub Container Registry
  uses: docker/login-action@v1
  with:
    registry: ghcr.io
    username: ${{ github.actor }}
    password: ${{ secrets.GITHUB_TOKEN }}

- name: Build and push Docker image
  uses: docker/build-push-action@v2
  with:
    context: .
    file: ./Dockerfile
    push: true
    tags: ghcr.io/hidalgosandra/a-devops:latest

- name: Test the built image
  run: |
    docker run --rm ghcr.io/${{ github.repository_owner }}/actions-adibidea:latest
